spring.application.name=razorpay
spring.datasource.url=jdbc:mysql://localhost:3306/payment_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key=rzp_test_SPFRod5m6DFyHr
razorpay.secret=UH58ncVYPCN6NfYkVWBxBmqJ