spring.application.name=razorpay
spring.datasource.url=jdbc:mysql://localhost:3306/payment_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key=rzp_test_SPzLabJpRLv5Hv
razorpay.secret=Q7XSw2p7iT6wnEMlpswH7Pxr

shiprocket.email=your_email
shiprocket.password=your_password
shiprocket.base-url=https://apiv2.shiprocket.in/v1/external